security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Ist\Bundle\EnsinameBundle\Entity\Professor:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_PROF:       ROLE_PROF
        # ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin: { password: 1234, roles: 'ROLE_ADMIN' }
        user_db:
            entity: { class: Ist\Bundle\EnsinameBundle\Entity\Professor, property: username }

    firewalls:
        admin_area:
            pattern:    ^/admin
            http_basic: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern: ^/login$
            security: false
        secured_area:
            pattern: ^/
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: 'ROLE_ADMIN, ROLE_PROF' }
        - { path: ^/admin, roles: ROLE_ADMIN }